# Railway Single Service Configuration (Option A)
# Deploys backend + frontend in one service

[build]
  builder = "NIXPACKS"
  # Build command will be: bun install && bun run build

[deploy]
  startCommand = "bun run src/server.ts"
  healthcheckPath = "/api/images"
  healthcheckTimeout = 100
  restartPolicyType = "ON_FAILURE"
  restartPolicyMaxRetries = 10

# Railway auto-detects Bun runtime
# Backend serves static files from src/web/dist in production

